name: PingMTR Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Bats
        uses: bats-core/bats-action@v3

      - name: Run Bats tests
        run: bats pingmtr_test.bats
